version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # Exposing this for external DB clients for your convenience
      - '5432:5432'
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
  prisma:
    build: 
      dockerfile: prismaProxy.dockerfile
    depends_on:
      - db
    ports: 
      - '3333:3333'
    environment:
      DATABASE_URL: "postgresql://johndoe:randompassword@db/mydb?schema=public"
  
  worker:
    build:
      dockerfile: ./worker.dockerfile
    depends_on:
      - db
      - prisma
    volumes:
      - ./:/worker
    ports:
      - '8787:8787'
    environment:
      ENVIRONMENT: development
volumes:
  pgdata: {}
