name = "cloudflare-workers-ts-graphql"
type = "javascript"
zone_id = ""
account_id = "4b53615f0f1c00b8a6c8b3d694848674"
route = ""
workers_dev = true
compatibility_date = "2022-01-11"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
